options:
  merge-default-rules: true
  max-warnings: 50

files:
  includes:
    - 'src/scss/**/*.scss'
    - 'src/scss-demo/**/*.scss'
  ignore:
    - 'node_modules/**/*.*'

rules:
  attribute-quotes: 2
  brace-style: '1tbs'
  border-zero: 1
  class-name-format:
    - 2
    -
      underscore: false
      convention: 'hyphenatedbem'
  empty-args: 0
  empty-line-between-blocks: 2
  extends-before-mixins: 2
  extends-before-declarations: 2
  final-newline: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 0
  placeholder-in-extend: 2
  leading-zero:
    - 2
    -
      include: true
  mixins-before-declarations:
    - 2
    -
      exclude: ['breakpoint', 'breakpointRange', 'mq', 'fz-loop', 'screen_only_breakpoint']
  mixin-name-format:
    - 0
  nesting-depth:
    - 2
    -
      max-depth: 3
  no-color-literals: 0
  no-empty-rulesets: 2
  no-trailing-whitespace: 0
  no-debug: 2
  no-ids: 2
  no-important: 0
  no-qualifying-elements: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 0
  hex-notation:
    - 2
    -
      style: 'uppercase'
  indentation:
    - 2
    -
      size: 2
  placeholder-name-format: 0
  property-sort-order:
    - 2
    -
      ignore-custom-properties: true
  pseudo-element: 0
  quotes: 'single'
  space-after-bang:
    - 2
    -
      include: false
  space-after-comma: 2
  space-after-colon:
    - 2
    -
      include: true
  trailing-semicolon:
    - 2
    -
      include: true
  url-quotes: 2
  variable-name-format: 0
  variable-for-property:
    - 0
    -
      properties: ['margin', 'content']
  zero-unit: 2
